yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
#главная страница
    path('', views.index, name='index'),
#страница группы 
    path('group/<slug:slug>/', views.group_posts, name = 'group_list'),   
    
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Главная страница
    path('', include('posts.urls', namespace = 'posts')),
    path('admin/', admin.site.urls),
    
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model() 


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, default=title)
    description = models.TextField()
    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    ) 
    group = models.ForeignKey(Group,
        blank=True, 
        null=True,
        on_delete=models.CASCADE)

yatube/posts/views.py
from django.shortcuts import HttpResponse

# Create your views here.

from django.shortcuts import render, get_object_or_404
from .models import Post,Group

# Главная страница
def index(request):    
    template = 'posts/index.html'

    posts = Post.objects.order_by('-pub_date')[:10]

    title = 'Последние обновления'
    context = {
        'title' : title,
        'posts' : posts
    }
    return render(request, template, context)


# Страница со списком групп
def group_posts(request,slug):
    

    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]

    title = 'Записи сообщества '+str(group)
    #text = 'Здесь будет информация о группах проекта Yatube'
    context = {
        'group': group,
        'posts' : posts,
        'title' : title
    }
    return render(request, 'posts/group_list.html', context)




    

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>   
  {% load static %}

      
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <title> {% block title %} {% endblock %}</title>
  </head>
  
  <body>
    <header>
      {% include 'includes/header.html' %} 
    </header>
    <main> 
    {% block content %}
      пустая часть контент шаблоне базы
    {% endblock %}
    </main>
     
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}   
    </footer>
  </body>

yatube/templates/includes/footer.html
<!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>   

yatube/templates/includes/header.html
{% load static %}



<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>     

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{title}}
{% endblock %}

{% block content %}
  {% for post in posts %}
  {{group.title}}
  <ul>
  Описание группы: {{group.description}}
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %} 

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
{{title}}
{% endblock %}


{% block content %}
    {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>    
  <a href="{% url 'posts:group_list' post.group.slug %} "> все записи группы</a>
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}  
{% endblock %}
  